<nav>
    <div class="logo">
        <a href="index.php"><img src="images/logo.png" alt="Logo"></a>
    </div>

    <div class="dropdown">
        <button class="dropbtn">Select an option...</button>
        <div class="dropdown-content">
            <a href="index.php">Home</a>
            <a href="pets.php">Pets</a>
            <a href="add.php">Add More</a>
            <a href="gallery.php">Gallery</a>
        </div>
    </div>
    <form id="form">
        <input type="search" id="query" name="q" placeholder="Search...">
        <div class="search">
            <button>
                <span class="material-symbols-outlined">search</span>
            </button>
        </div>
    </form>
</nav>